Add a config to pull all keys from a JSON-based secret and apply each key in the JSON as an environment variable.
seek-oss/aws-sm-buildkite-plugin pull request #11
Opened 2019-07-16 13:56 UTC by underscorebrody

This is useful when you have a large number of environment variables that need to be set from a single secret.

2019-09-11 23:51 UTC, zsims commented
Hi sorry for the (huge) delay in getting to this, I totally missed the notification 😄

2019-09-12 00:01 UTC, zsims requested changes
Some minor feedback, let me know if I should update this given the long time it took for me to review :(

2019-09-12 00:01 UTC, zsims commented on README.md
> +            json-key: ".Variables"
Does `.` work here to get all the keys? e.g. in the case of key-value AWS SM secrets?

2019-09-12 00:01 UTC, zsims commented on hooks/environment
> +  for s in $(echo ${secret_value} | jq "${json_key} | to_entries[]" | jq -r '.key + "=" + .value'); do
We probably need to handle keys that have spaces in them, e.g. `sed 's/ /_/g'` or similar

2019-09-12 00:01 UTC, zsims commented on tests/test.bats
> +@test "Fetches all environment variables from JSON without JSON key" {
Nice tests :)

2019-09-12 00:01 UTC, zsims commented on hooks/environment
> +  for s in $(echo ${secret_value} | jq "${json_key} | to_entries[]" | jq -r '.key + "=" + .value'); do
I think this loop will break on spaces within secret keys or values, worth at least adding a test to this effect.

E.g.

```
$ export json_key='.'
$ export secret_value='{"a":"v1", "b": "v2 v3", "c d": "v4"}'
$ for s in $(echo ${secret_value} | jq "${json_key} | to_entries[]" | jq -r '.key + "=" + .value'); do
for> echo "$s"
for> done
a=v1
b=v2
v3
c
d=v4
```

2020-04-21 13:33 UTC, CHR15- commented
@zsims any plans to get this in?

2020-05-03 23:42 UTC, zsims commented
> @zsims any plans to get this in?

I'll try pick this up, few balls in the air at the moment. But shouldn't be too hard :)

2020-05-04 13:26 UTC, underscorebrody commented
Thanks for taking this over the line @zsims , I'm not able to test out any changes to it as I'm unfortunately not using buildkite on my current project.

2020-05-06 05:17 UTC, zsims commented
I've addressed the feedback in #15 so secrets with whitespaces don't break. Thanks again for your PR :-)

2020-05-06 05:17 UTC, merged

2020-05-06 05:23 UTC, zsims commented
This is in https://github.com/seek-oss/aws-sm-buildkite-plugin/releases/tag/v2.1.0 @CHR15- @underscorebrody